### ISSUE TITLE
test_transaction fails in Azurite

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#297]
The test_transaction fails 
test table::clients::partition_key_client::integration_tests::test_transaction ... FAILED

I think this is due to https://github.com/Azure/Azurite/issues/792 where it is just not supported yet in Azurite.

```
azurite -d azurite.log

$env:AZURE_STORAGE_ACCOUNT="devstoreaccount1"
$env:AZURE_STORAGE_KEY="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
cargo test --features test_integration test_transaction
```

The request is:
```
POST http://127.0.0.1:10002/devstoreaccount1/$batch HTTP/1.1
content-length: 915
content-type: multipart/mixed; boundary=batch_93e29533-82b3-4ed8-9439-fc40dd3242c9
x-ms-date: Mon, 14 Jun 2021 21:57:52 GMT
x-ms-version: 2019-12-12
authorization: SharedKey devstoreaccount1:kCYIWFkLqKCC2w2NeQXoWjDAIfHaQ3wKWGjEQjyuYxc=
accept: */*
host: 127.0.0.1:10002

--transaction_93e29533-82b3-4ed8-9439-fc40dd3242c9
Content-Type: multipart/mixed; boundary=changeset_ddf52622-28d4-466e-bd34-3d5df4ce8087

--changeset_ddf52622-28d4-466e-bd34-3d5df4ce8087
Content-Type: application/http
Content-Transfer-Encoding: binary

POST http://127.0.0.1:10002/devstoreaccount1/PartitionKeyClientTransaction HTTP/1.1
accept: application/json;odata=fullmetadata
content-type: application/json

{"PartitionKey":"Milan","name":"Francesco","RowKey":"Cogno"}
--changeset_ddf52622-28d4-466e-bd34-3d5df4ce8087
Content-Type: application/http
Content-Transfer-Encoding: binary

POST http://127.0.0.1:10002/devstoreaccount1/PartitionKeyClientTransaction HTTP/1.1
accept: application/json;odata=fullmetadata
content-type: application/json

{"PartitionKey":"Milan","name":"Francesco","RowKey":"Potter"}

--changeset_ddf52622-28d4-466e-bd34-3d5df4ce8087--
--transaction_93e29533-82b3-4ed8-9439-fc40dd3242c9
```

With azurite 3.12.0 returning:
```
HTTP/1.1 500 Internal Server Error
Server: Azurite-Table/3.13.1
Date: Mon, 14 Jun 2021 21:57:52 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 0
```

This looks like the relavant part of the log:
```
2021-06-14T22:10:40.904Z ce55097a-24bc-47b4-8723-a00c23a40421 error: ErrorMiddleware: ErrorName=TypeError ErrorMessage=console_1.exception is not a function ErrorStack="TypeError: console_1.exception is not a function\n    at TableBatchSerialization.extractBatchBoundary (C:\\Users\\cataggar\\.fnm\\node-versions\\v14.15.1\\installation\\node_modules\\azurite\\dist\\src\\common\\batch\\BatchSerialization.js:30:29)\n    at TableBatchSerialization.deserializeBatchRequest (C:\\Users\\cataggar\\.fnm\\node-versions\\v14.15.1\\installation\\node_modules\\azurite\\dist\\src\\table\\batch\\TableBatchSerialization.js:36:14)\n    at TableBatchOrchestrator.processBatchRequestAndSerializeResponse (C:\\Users\\cataggar\\.fnm\\node-versions\\v14.15.1\\installation\\node_modules\\azurite\\dist\\src\\table\\batch\\TableBatchOrchestrator.js:43:51)\n    at TableHandler.batch (C:\\Users\\cataggar\\.fnm\\node-versions\\v14.15.1\\installation\\node_modules\\azurite\\dist\\src\\table\\handlers\\TableHandler.js:400:50)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
2021-06-14T22:10:40.904Z ce55097a-24bc-47b4-8723-a00c23a40421 error: ErrorMiddleware: Set HTTP code: 500
```

**Comment by rylev** [comment]
Looks like https://github.com/Azure/Azurite/issues/792 has been fixed with https://github.com/Azure/Azurite/pull/830. Can we turn the test be reenabled now?

**Comment by ctaggart** [comment]
After a release is made, we can try it out.  It will be in the release after 3.13.1.

> Upcoming Release
Added support for PATCH Verb in Table Batch Operations / Entity Group Transactions.
https://github.com/Azure/Azurite/blob/master/ChangeLog.md

**Comment by rylev** [comment]
@ctaggart is this still an issue?
